### ISSUE TITLE
Empty strings in array

### ISSUE THREAD

**Issue by fahadsiddiqui** [fahadsiddiqui/gochunker#2]
The array being appended has empty strings at the end. This happens because of `append(chunks, ...)` function—which auto expands `chunks`. We need to avoid doing this. Fix it.

**Comment by Ammar022** [comment]
I have executed program by giving long input as well. I can't figure out what's exactly the problem is. Can you please explain in more detail?

**Comment by fahadsiddiqui** [comment]
The program surely runs fine just because I am not printing any empty lines in `main.go`. The function is still returning the empty strings in the array. We don't want to return empty strings.
